# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x11moonlang.metadata\"(\n\x11QueryCacheRequest\x12\x13\n\x0bprefix_hash\x18\x01 \x01(\t\"G\n\rCacheLocation\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nkv_indices\x18\x02 \x03(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"I\n\x12QueryCacheResponse\x12\x33\n\tlocations\x18\x01 \x03(\x0b\x32 .moonlang.metadata.CacheLocation\"P\n\x14RegisterCacheRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x13\n\x0bprefix_hash\x18\x02 \x01(\t\x12\x12\n\nkv_indices\x18\x03 \x03(\x05\"9\n\x15RegisterCacheResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"j\n\nNodeStatus\x12\x18\n\x10\x61vailable_memory\x18\x01 \x01(\x03\x12\x14\n\x0ctotal_memory\x18\x02 \x01(\x03\x12\x17\n\x0f\x61\x63tive_requests\x18\x03 \x01(\x05\x12\x13\n\x0bload_factor\x18\x04 \x01(\x01\"Y\n\x17UpdateNodeStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12-\n\x06status\x18\x02 \x01(\x0b\x32\x1d.moonlang.metadata.NodeStatus\"+\n\x18UpdateNodeStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbd\x02\n\x0fMetadataService\x12Y\n\nQueryCache\x12$.moonlang.metadata.QueryCacheRequest\x1a%.moonlang.metadata.QueryCacheResponse\x12\x62\n\rRegisterCache\x12\'.moonlang.metadata.RegisterCacheRequest\x1a(.moonlang.metadata.RegisterCacheResponse\x12k\n\x10UpdateNodeStatus\x12*.moonlang.metadata.UpdateNodeStatusRequest\x1a+.moonlang.metadata.UpdateNodeStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYCACHEREQUEST']._serialized_start=37
  _globals['_QUERYCACHEREQUEST']._serialized_end=77
  _globals['_CACHELOCATION']._serialized_start=79
  _globals['_CACHELOCATION']._serialized_end=150
  _globals['_QUERYCACHERESPONSE']._serialized_start=152
  _globals['_QUERYCACHERESPONSE']._serialized_end=225
  _globals['_REGISTERCACHEREQUEST']._serialized_start=227
  _globals['_REGISTERCACHEREQUEST']._serialized_end=307
  _globals['_REGISTERCACHERESPONSE']._serialized_start=309
  _globals['_REGISTERCACHERESPONSE']._serialized_end=366
  _globals['_NODESTATUS']._serialized_start=368
  _globals['_NODESTATUS']._serialized_end=474
  _globals['_UPDATENODESTATUSREQUEST']._serialized_start=476
  _globals['_UPDATENODESTATUSREQUEST']._serialized_end=565
  _globals['_UPDATENODESTATUSRESPONSE']._serialized_start=567
  _globals['_UPDATENODESTATUSRESPONSE']._serialized_end=610
  _globals['_METADATASERVICE']._serialized_start=613
  _globals['_METADATASERVICE']._serialized_end=930
# @@protoc_insertion_point(module_scope)
