# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import metadata_pb2 as metadata__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in metadata_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetadataServiceStub(object):
    """Metadata service for global KV cache coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryCache = channel.unary_unary(
                '/moonlang.metadata.MetadataService/QueryCache',
                request_serializer=metadata__pb2.QueryCacheRequest.SerializeToString,
                response_deserializer=metadata__pb2.QueryCacheResponse.FromString,
                _registered_method=True)
        self.RegisterCache = channel.unary_unary(
                '/moonlang.metadata.MetadataService/RegisterCache',
                request_serializer=metadata__pb2.RegisterCacheRequest.SerializeToString,
                response_deserializer=metadata__pb2.RegisterCacheResponse.FromString,
                _registered_method=True)
        self.UpdateNodeStatus = channel.unary_unary(
                '/moonlang.metadata.MetadataService/UpdateNodeStatus',
                request_serializer=metadata__pb2.UpdateNodeStatusRequest.SerializeToString,
                response_deserializer=metadata__pb2.UpdateNodeStatusResponse.FromString,
                _registered_method=True)


class MetadataServiceServicer(object):
    """Metadata service for global KV cache coordination
    """

    def QueryCache(self, request, context):
        """Query which nodes have a specific cache prefix
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCache(self, request, context):
        """Register local cache with the metadata server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodeStatus(self, request, context):
        """Update node status (capacity, load, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryCache': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCache,
                    request_deserializer=metadata__pb2.QueryCacheRequest.FromString,
                    response_serializer=metadata__pb2.QueryCacheResponse.SerializeToString,
            ),
            'RegisterCache': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCache,
                    request_deserializer=metadata__pb2.RegisterCacheRequest.FromString,
                    response_serializer=metadata__pb2.RegisterCacheResponse.SerializeToString,
            ),
            'UpdateNodeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNodeStatus,
                    request_deserializer=metadata__pb2.UpdateNodeStatusRequest.FromString,
                    response_serializer=metadata__pb2.UpdateNodeStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'moonlang.metadata.MetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('moonlang.metadata.MetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataService(object):
    """Metadata service for global KV cache coordination
    """

    @staticmethod
    def QueryCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moonlang.metadata.MetadataService/QueryCache',
            metadata__pb2.QueryCacheRequest.SerializeToString,
            metadata__pb2.QueryCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moonlang.metadata.MetadataService/RegisterCache',
            metadata__pb2.RegisterCacheRequest.SerializeToString,
            metadata__pb2.RegisterCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/moonlang.metadata.MetadataService/UpdateNodeStatus',
            metadata__pb2.UpdateNodeStatusRequest.SerializeToString,
            metadata__pb2.UpdateNodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
